name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu_Latest_GCC",
            os: ubuntu-latest,
            artifact: "ubuntu_gcc.7z",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            archiver: "7z a",
            generators: "Ninja"
          }
    runs-on: ${{ matrix.config.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Print enviroment
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
    - name: Install dependencies on ubuntu
      if: startsWith(matrix.config.name, 'Ubuntu_Latest_GCC')
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build cmake python3.9-dev python3-pip python3-setuptools python3-wheel python3-wheel libglfw3 libglfw3-dev
        ninja --version
        cmake --version
        gcc --version
        python3.9 --version
        python3.9 -m pip install numpy
        sudo apt-get install python3-numpy
    - name: Configure
      shell: bash
      run: |
        mkdir build
        mkdir instdir
        cmake \
          -S . \
          -B . \
          -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
          -G "${{ matrix.config.generators }}" \
          -DCMAKE_INSTALL_PREFIX:PATH=instdir
    - name: Build
      shell: bash
      run: cmake --build . --config ${{ matrix.config.build_type }}
    - name: Install Strip
      shell: bash
      run: cmake --install . --strip
